# Generated by Django 5.1.7 on 2025-03-25 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo_recebimento', models.IntegerField()),
                ('propagandas', models.IntegerField()),
                ('materia_prima', models.IntegerField()),
                ('prazo_pagamento', models.IntegerField()),
                ('funcionarios', models.IntegerField()),
                ('reajuste', models.DecimalField(decimal_places=2, max_digits=5)),
                ('treinamento', models.BooleanField(default=False)),
                ('maquinas', models.IntegerField()),
                ('emprestimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('antecipacao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.empresa')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.rodada')),
            ],
        ),
    ]
