# Generated by Django 5.1.7 on 2025-03-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0003_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='decisao',
            old_name='maquinas',
            new_name='compra_maquinas',
        ),
        migrations.RenameField(
            model_name='decisao',
            old_name='reajuste',
            new_name='juros',
        ),
        migrations.RenameField(
            model_name='decisao',
            old_name='materia_prima',
            new_name='prazo',
        ),
        migrations.RenameField(
            model_name='decisao',
            old_name='preco_venda',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='decisao',
            old_name='prazo_pagamento',
            new_name='propaganda',
        ),
        migrations.RemoveField(
            model_name='decisao',
            name='data_envio',
        ),
        migrations.RemoveField(
            model_name='decisao',
            name='prazo_recebimento',
        ),
        migrations.RemoveField(
            model_name='decisao',
            name='propagandas',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='capital_inicial',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='saldo_caixa',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='antecipacoes',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='custos',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='emprestimos',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='folha_pagamento',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='gerado_em',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='maquinas',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='saldo_final',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='treinamentos',
        ),
        migrations.RemoveField(
            model_name='rodada',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='rodada',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='rodada',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='rodada',
            name='encerrada',
        ),
        migrations.AddField(
            model_name='resultado',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='resultado',
            name='despesa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='patrimonio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodada',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decisao',
            name='antecipacao',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='decisao',
            name='emprestimo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='lucro',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='receita',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
