# Generated by Django 5.1.7 on 2025-03-26 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0002_decisao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receita', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('folha_pagamento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('treinamentos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maquinas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('emprestimos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('antecipacoes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.empresa')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.rodada')),
            ],
        ),
    ]
