# Generated by Django 5.1.7 on 2025-03-27 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0004_parametroglobal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisao',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodada',
            name='data_abertura',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rodada',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
